services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
    env_file:
      - .env
    command: bash -c "uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"