"""check symbols

Revision ID: 7ef545d69f2f
Revises: 190d25b9cc44
Create Date: 2024-12-16 19:55:28.823701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ef545d69f2f'
down_revision: Union[str, None] = '190d25b9cc44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('check_symbols', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'check_symbols')
    # ### end Alembic commands ###
